import { ShieldAlert } from "lucide-react";

export function Disclaimer({ className = "" }: { className?: string }) {
  return (
    <div
      className={`flex gap-3 rounded-lg border border-border bg-muted/60 p-4 text-sm text-muted-foreground ${className}`}
    >
      <ShieldAlert className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden />
      <p>
        <span className="font-semibold text-foreground">Responsible AI notice:</span> WISE WIZARD
        Assistant provides general workplace-rights and safety information generated by AI. It can
        be incomplete or inaccurate and is not legal advice. Always review and edit outputs, and
        confirm with your union representative, health &amp; safety officer, or a qualified labour
        lawyer before acting.
      </p>
    </div>
  );
}
